primary: &primary
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

secondary: &secondary
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *primary
    database: my_app_development
  cache:
    <<: *secondary
    database: storage/cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *secondary
    database: storage/queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *secondary
    database: storage/cable.sqlite3
    migrations_paths: db/cable_migrate


test:
  <<: *primary
  database: my_app_test


production:
  primary: &primary_production
    <<: *primary
    database: my_app_production
    username: my_app
    password: <%= ENV["MY_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: my_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_app_production_cable
    migrations_paths: db/cable_migrate
